# Tasks to do only on the production server.

# Setup NFS mounts where file attachments will be stored.
# This is so files are backed up on the NFS host; when hosting
# redmine on a VM without a backup client.
# 
# Be sure the UID for the redmine user matches with the
# NFS server

- file: path='{{ redmine_files_nfs_mount }}'
        state=directory
  sudo: yes

- mount: name='{{ redmine_files_nfs_mount }}'
         src='{{ redmine_files_nfs_source }}'
         fstype=nfs
         opts=rsize=32768,wsize=32768,tcp,hard,nointr
         state=mounted
  sudo: yes

- name: set attachments_storage_path in configuration.yml
  lineinfile: >
      dest='{{ redmine_root_dir }}/config/configuration.yml'
      regexp='\s*attachments_storage_path:'
      line='  attachments_storage_path: {{ redmine_files_nfs_mount }}'
  notify: restart nginx