---

- import_tasks: system.yml
  tags: system

- import_tasks: firewall.yml
  tags: firewall

- import_tasks: database.yml
  tags: database
  when: do_database_management == True

- import_tasks: redmine.yml 
  tags: redmine

- import_tasks: nginx.yml 
  tags: nginx

- import_tasks: attachments_storage.yml
  tags: attachments_storage
  when: is_production_vm == True
