---

- include: system.yml tags=system

- include: firewall.yml tags=firewall
  when: is_production_vm == True

- include: database.yml tags=database
  when: do_database_management == True

- include: redmine.yml tags=redmine

- include: nginx.yml tags=nginx

- include: attachments_storage.yml tags=attachments_storage
  when: is_production_vm == True
