---
# handlers file for easyredmine

- name: restart nginx
  service: name=nginx
           state=restarted
  become: yes

- name: restart firewalld
  service: name=firewalld
           state=restarted
  become: yes

- name: rebuild mail aliases
  command: /usr/bin/newaliases
  become: yes
