easyredmine_login_bg_img: login-bg-58894778db89f0c55f5aa371eff62b7475325258f4308e9c286f988a37e0e44b.jpg
redmine_mail_alias: redmine@localhost
redmine_owner: vagrant
redmine_uid: ''
redmine_owner_ssh_pub_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHpZ5BcVJmF76N4jIlH7N4pdP7Wa/d354zTrGp+/VIXFJhNwOM/xdZLXAGogZpzu5jnMzikcj6jUVoidCUl41C2QTTpebdxCUagsoLi6BA/gNyvSi9iSZuPhFuJc3OvQLUoiQ6uXRjEdMh/KmF73I7aMo4zsC2VViCPFecDJSAIIDB9CrLLGkJF9yddNRVLPOlFFaKGUTz/Z8E30NhTgSGsTizw4wsdwqASmtXBAKFGaQ2qjRe8nq05dKzHsCXPh1tgPeg+z7H/LiKPWREnx0bO1q9VuOqahPUHiacP7+8IVmknLVYyM42YIQUuWcXrTVL3lWxjD+1IFYCVQfN4BLX mheiges@korlan.local
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2SqMq4NgxheuQbiv6v3F6DhosI5SaX7U/L0H1nrKFxBHkJLQpV1YZ9n2GsGxRCUYd483yYzcRAZuHbtRcg9FRfytGXhEw9QYGqcIH6PX6g377tKl2FhnYUcUwDLvhmH7HDZgvbYK1b9aoKW9wIF8Ass55li64Wxj6ytMHdZq8USFLE+wlKiH/Ifu7TlLl6wbUSsURv+bV1aFCrUFy1WTF2fjC1+cvVIyZhY9kxW7iaI7y8t/U31LPDF/9beYBjjhpaAl3BfAcC/jevh1jKhKOKMLo4Lda75Ays28V7Tk6To79eLkaD+Nd+7yzzL+k473hHaLxpBU18oiPkmZQcYvj bob@umari 
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvzPrTJ3y9gxqQGiIXd3IPJyxyZEpGS0377aaJPD7DkALes0KDys12SosrEL5o5tJLBrn3xIEGhStBqf6f+AduyKsaSz6FNDAurbYzjZ9qmtJmYekhlCOuQ9+8qeaCURvaqmGT1uQRg4/bq5nBSRMAJI8qvg2zRq/5ESKnDHzvDkDTvfiSv9cR9Tlm3giBqo834BwNIMCZsHijy10SSkbyiC4hsBnjSzSFtDsHjllbA6088upphFlMhIrDh8E5kIEKn+Z4hPIYi5D7XlJU0uMZzr58aHohzmVqEqsqHOoYctAOhuNEOeLZxMGM21UuKb+h4IL4Qjj55Hcf2shSKFNp drew@roci.ctegd.uga.edu 
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtw+JxATbOr6wp7MLZWyk1F9AOBghX0ZH14MMvERQ545Ye5MgJ6m14gSxrqk5nOcpRXja6B3foWfNfBxShx8FELSXgw8EAiQo9ARrYu4XG5TdOYgY4gty3QRqaWbmLvwrFnN1NMNd6FqmVxgD+nMj66NLJLsOGDaVyuz7ArE3EQAhchcPIUJwfmobiBOdXhKsD5IPwqvZqkR8JnkkVa9g3wW4qbUqzMmmRASRGEiiKt0SNDY6BXjZblMUh1fPtZd5w/VQn4/klVAn2OhyJPlmdZI5CjP480IxHCcRtb7W1YXEbg988PgUo2lW4hpUNYtM61mRjZjQqw4cbFkfJJwoH drewp
root_ssh_pub_keys: {{ redmine_owner_ssh_pub_keys }}
do_database_management: yes
do_redmine_db_import: yes # no import unless do_database_management is also yes
do_redmine_installer: yes
remote_scratch_path: /vagrant/scratch
nginx_pem: redmine.vm-rsa.pem
installer_package_name: easyredmine-upen-20180412.zip #easyredmine_2016_stable_u2072_v2018_1_1__platform_2018_02_04.zip
installer_package_path: '{{ remote_scratch_path }}/{{ installer_package_name }}'
installer_package_url: 'http://software.apidb.org/source/{{ installer_package_name }}'
redmine_db_dump_file: '{{ remote_scratch_path }}/redmine_dump.sql.gz'
redmine_root_dir: /opt/easyredmine
mysql_admin_login: root
mysql_admin_password: ''
redmine_db_service_provider: mariadb # or mysqld
redmine_db_name: easyredmine
redmine_db_host: localhost
redmine_db_user: redmine
redmine_db_password: '@redmin3r'
redmine_db_encoding: utf8
redmine_db_port: 3306
smtp_address: localhost
smtp_port: 587
smtp_domain: smtpdomain
smtp_username: smtpuser
smtp_password: smtppassword
smtp_authentication: plain
smtp_enable_starttls: yes
smtp_openssl_verify_mode: peer
swap_add_mb: 512
ruby_version: 2.4.1
is_production_vm: no
redmine_files_nfs_mount: ''  # /mnt/redminefiles
redmine_files_nfs_source: '' # 171.26.20.75:/srv/easyredmine
_redmine_db_import_file: /tmp/redmine_dump.sql
_redmine_db_import_success: /tmp/redmine_db_import_success
_redmine_install_wrapper: '/home/{{ redmine_owner }}/install_wrapper'

# rvm1-ansible module vars
rvm1_rubies:
  - 'ruby-{{ ruby_version }}'
rvm1_bundler_install: yes
rvm1_install_path: '/home/{{ redmine_owner }}/.rvm'
rvm1_rvm_check_for_updates: no
rvm1_user: '{{ redmine_owner }}'
