easyredmine_login_bg_img: login-bg-58894778db89f0c55f5aa371eff62b7475325258f4308e9c286f988a37e0e44b.jpg
redmine_mail_alias: redmine@localhost
redmine_owner: vagrant
redmine_uid: ''
redmine_owner_ssh_pub_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAvijH8y7CL9TxWCucjgXRa2q3l0Nc9JW7/SAFHVgt/FYClenS0DMN0nGm1I4z2mtftt8gHz5f6PNqyvfc3F0JcOqiuH9qP79FQ6c8rDmqQEqOuBrufPX11y/9IESIJ0aQ5feQP+WooR6bo/O7BFJS005S3foA/iLphf+smLrW44k= mheiges@sapote.local
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIBKXyFF/K1AT52FGrq5Z27guGgHDELy8W8NInAgrDQZQP+U5ORs9wB8SsuD8vyhYy3G2Tz8xAKCxWcFHvuNDv4VIg8D6ge7VMdWHGtbS8UC153dK3mMQ+CMTgJsezqgk0j4/ot7LaQ6yurb8t27TOHeqEdHyB5O/eL6pYntsKqEWQ== mguidry@uga.edu
do_database_management: True
do_redmine_db_import: True # no import unless do_database_management is also true
do_redmine_installer: True
remote_scratch_path: /vagrant/scratch
nginx_pem: redmine.vm-rsa.pem
installer_package_name: easyredmine_2016_stable_u2072_v2016_03_07.zip
installer_package_path: '{{ remote_scratch_path }}/{{ installer_package_name }}'
installer_package_url: 'http://software.apidb.org/source/{{ installer_package_name }}'
redmine_db_dump_file: '{{ remote_scratch_path }}/redmine_dump.sql.gz'
redmine_root_dir: /opt/easyredmine
mysql_admin_login: root
mysql_admin_password: ''
redmine_db_service_provider: mariadb # or mysqld
redmine_db_name: easyredmine
redmine_db_host: localhost
redmine_db_user: redmine
redmine_db_password: '@redmin3r'
redmine_db_encoding: utf8
redmine_db_port: 3306
smtp_address: localhost
smtp_port: 587
smtp_domain: smtpdomain
smtp_username: smtpuser
smtp_password: smtppassword
smtp_authentication: plain
smtp_enable_starttls: true
ruby_version: 2.1.3
is_production_vm: False
redmine_files_nfs_mount: ''  # /mnt/redminefiles
redmine_files_nfs_source: '' # 171.26.20.75:/srv/easyredmine
_redmine_db_import_file: /tmp/redmine_dump.sql
_redmine_db_import_success: /tmp/redmine_db_import_success
_redmine_install_wrapper: '/home/{{ redmine_owner }}/install_wrapper'

# rvm1-ansible module vars
rvm1_rubies:
  - 'ruby-{{ ruby_version }}'
rvm1_rvm_check_for_updates: False

